### ISSUE TITLE
No module named 'fpdf'

### ISSUE THREAD

**Issue by FreeCutter** [alekssadowski95/FreeCAD-Beginner-Assistant#13]
Hi, I'm curious to see what the WB is about.

However, while starting the WB / apply WB to a file being open I got the following error messages:

![grafik](https://github.com/user-attachments/assets/5d8783a1-a756-4806-aee7-6bff0e00b247)

and Report View tells me:

`07:03:06  No module named 'fpdf'
07:03:06  Traceback (most recent call last):
  File "C:\Users\...\AppData\Roaming\FreeCAD\Mod\FreeCAD-Beginner-Assistant-main\.\InitGui.py", line 37, in Initialize
    from commands import AnalyseDocumentCommand
  File "C:\Program Files\FreeCAD 1.0\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\AppData\Roaming\FreeCAD\Mod\FreeCAD-Beginner-Assistant-main\.\commands.py", line 8, in <module>
    from pdfgen import run_report
  File "C:\Program Files\FreeCAD 1.0\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\AppData\Roaming\FreeCAD\Mod\FreeCAD-Beginner-Assistant-main\.\pdfgen.py", line 1, in <module>
    from fpdf import FPDF
  File "C:\Program Files\FreeCAD 1.0\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`

**FreeCAD Version info:**
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 1.0.0RC2.38806 (Git)
Build type: Release
Branch: (HEAD detached at 1.0rc2)
Hash: 3d63fc6c2f665a8d5e6468845a419bcac80756c7
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * A2plus 0.4.68
  * Assembly4 0.50.15
  * CurvedShapes 1.0.10
  * Curves 0.6.48
  * fasteners 0.5.29
  * FreeCAD-Beginner-Assistant-main 1.0.0
  * Ondsel-Lens 2024.9.13.02
  * Render 2024.9.25
  * SelectorToolbar

**Comment by alekssadowski95** [comment]
Thank you for your bug report! I added the fpdf library as a static dependency. Its LGPLv3 so it should be compatible. Does it work on your side now?

**Comment by FreeCutter** [comment]
Thanks for your quick responds.

Starting the workbench now results into messages in Report View:

`08:21:19  attempted relative import with no known parent package`
`08:21:19  Traceback (most recent call last):`
   `File "C:\Users\...\AppData\Roaming\FreeCAD\Mod\FreeCAD-Beginner-Assistant-main\.\InitGui.py", line 37, in Initialize
    from commands import AnalyseDocumentCommand`
   `File "C:\Program Files\FreeCAD 1.0\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\feature.py", line 139, in _import`
    `return original_import(name, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
`  File "C:\Users\...\AppData\Roaming\FreeCAD\Mod\FreeCAD-Beginner-Assistant-main\.\commands.py", line 8, in <module>
    from pdfgen import run_report`
`  File "C:\Program Files\FreeCAD 1.0\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
`  File "C:\Users\...l\AppData\Roaming\FreeCAD\Mod\FreeCAD-Beginner-Assistant-main\.\pdfgen.py", line 1, in <module>
    from .fpdf import FPDF`
`  File "C:\Program Files\FreeCAD 1.0\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`

**FreeCAD version info:**
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 1.0.0RC2.38806 (Git)
Build type: Release
Branch: (HEAD detached at 1.0rc2)
Hash: 3d63fc6c2f665a8d5e6468845a419bcac80756c7
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * A2plus 0.4.68
  * Assembly4 0.50.15
  * CurvedShapes 1.0.12
  * Curves 0.6.50
  * fasteners 0.5.29
  * FreeCAD-Beginner-Assistant-main 1.0.0
  * Ondsel-Lens 2024.9.13.02
  * Render 2024.9.25
  * SelectorToolbar

**Comment by catmaps** [comment]
I have the very same problem when running FreeCAD_1.0.0-conda-Windows-x86_64-py311.7z  on a Windows 10 machine.

**Comment by Novite5** [comment]
This happens also on Arch Linux, even though python-fpdf2 has been installed.
