### ISSUE TITLE
Bug when trying to generate a report

### ISSUE THREAD

**Issue by 0phiTeS** [alekssadowski95/FreeCAD-Beginner-Assistant#9]
13:39:45  Running the Python command 'Analyse_Document_Command' failed:
Traceback (most recent call last):
  File "C:\Users\*User*\AppData\Roaming\FreeCAD\Mod\FreeCAD-Beginner-Assistant-main\.\commands.py", line 34, in Activated
    result_dict = generate_result_dict()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\*User*\AppData\Roaming\FreeCAD\Mod\FreeCAD-Beginner-Assistant-main\.\assistant.py", line 460, in generate_result_dict
    screenshot_abs_path = FreeCADGui.activeDocument().activeView().saveImage("C:\\Users\\Aleksander\\Documents\\GitHub\\FreeCAD-Beginner-Assistant\\model_images\\test.png", 1543, 822, 'Transparent')

**Comment by 0phiTeS** [comment]
I changed every hard coded dependency and it worked

**Comment by alekssadowski95** [comment]
This has been resolved in PR #10. Thank you for submitting a bug report :)

**Comment by alekssadowski95** [comment]
This has been resolved in PR #10. Thank you for submitting your bug report :)
